PKG_NAME = libmicrohttpd
PKG_VERS = 0.9.59
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://ftp.gnu.org/gnu/$(PKG_NAME)/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = http://www.gnu.org/software/libmicrohttpd/
COMMENT  = GNU libmicrohttpd is a small C library that is supposed to make it easy to run an HTTP server as part of another application
LICENSE  = LGPL

GNU_CONFIGURE = 1
CONFIGURE_ARGS = 

include ../../mk/spksrc.cross-cc.mk
